const mongoose = require('mongoose');

const challengeQueueSchema = new mongoose.Schema({
    '0': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '200': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '400': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '600': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '800': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '1000': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '1400': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '1800': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '2300': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '2800': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '3500': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '4000': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '4600': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '5200': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '5800': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '6400': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    '7000': {
        '0': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '10': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '20': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '30': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '40': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '50': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '60': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '70': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '80': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '90': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '100': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '120': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '140': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '160': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '180': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '200': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '230': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
        '260': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }],
    },
    'extra': {
        'extra': [{ userId: mongoose.Schema.Types.ObjectId, challengeId: mongoose.Schema.Types.ObjectId }]
    }
});

mongoose.model('ChallengeQueue', challengeQueueSchema);