export const AUTH_SING_UP_VALIDATE_EMAIL = 'AUTH_SING_UP_VALIDATE_EMAIL'
export const AUTH_SIGN_UP_VALIDATE_USERNAME = 'AUTH_SIGN_UP_VALIDATE_USERNAME';
export const AUTH_SIGN_UP_SEND_DATA = 'AUTH_SIGN_UP_SEND_DATA';
export const AUTH_SIGN_UP_WIPE_DATA = 'AUTH_SIGN_UP_WIPE_DATA';
export const AUTH_SIGN_IN_SEND_DATA = 'AUTH_SIGN_IN_SEND_DATA';
export const AUTH_SIGN_IN_WIPE_DATA = 'AUTH_SIGN_IN_WIPE_DATA';
export const AUTH_SIGN_OUT_SEND_DATA = 'AUTH_SIGN_OUT_SEND_DATA';