export const FETCH_FRIENDS_DATA = 'FETCH_FRIENDS_DATA';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export const DELETE_FRIEND = 'DELETE_FRIEND';