export const FETCH_APP_NOTIFICATION = 'FETCH_APP_NOTIFICATION';
export const RECEIVE_NOTIFICATION_FRIENDS = 'RECEIVE_NOTIFICATION_FRIENDS';
export const RECEIVE_NOTIFICATION_MESSENGER = 'RECEIVE_NOTIFICATION_MESSENGER';
export const RECEIVE_NOTIFICATION_CHALLENGES_REQUEST = 'RECEIVE_NOTIFICATION_CHALLENGES_REQUEST';
export const RECEIVE_NOTIFICATION_CHALLENGES_TURN = 'RECEIVE_NOTIFICATION_CHALLENGES_TURN';