// profile
export const SEND_SETTINGS_PROFILE_AVATAR = 'SEND_SETTINGS_PROFILE_AVATAR';
export const FETCH_SETTINGS_PROFILE_DATA = 'FETCH_SETTINGS_PROFILE_DATA';
export const SEND_SETTINGS_PROFILE_DATA = 'SEND_SETTINGS_PROFILE_DATA';
export const WIPE_SETTINGS_PROFILE_DATA = 'WIPE_SETTINGS_PROFILE_DATA'

// messenger
export const FETCH_SETTINGS_MESSENGER_DATA = 'FETCH_SETTINGS_MESSENGER_DATA';
export const SEND_SETTINGS_MESSENGER_DATA = 'SEND_SETTINGS_MESSENGER_DATA';
export const WIPE_SETTINGS_MESSENGER_DATA = 'WIPE_SETTINGS_MESSENGER_DATA';

// privacy
export const FETCH_SETTINGS_PRIVACY_DATA = 'FETCH_SETTINGS_PRIVACY_DATA';
export const SEND_SETTINGS_PRIVACY_DATA = 'SEND_SETTINGS_PRIVACY_DATA';
export const WIPE_SETTINGS_PRIVACY_DATA = 'WIPE_SETTINGS_PRIVACY_DATA';

// Other
// Account
export const FETCH_SETTINGS_OTHER_ACCOUNT_DATA = 'FETCH_SETTINGS_OTHER_ACCOUNT_DATA';
export const SETTINGS_OTHER_ACCOUNT_VALIDATE_EMAIL = 'SETTINGS_OTHER_ACCOUNT_VALIDATE_EMAIL';
export const SETTINGS_OTHER_ACCOUNT_VALIDATE_USERNAME = 'SETTINGS_OTHER_ACCOUNT_VALIDATE_USERNAME';
export const SETTINGS_OTHER_ACCOUNT_SEND_EMAIL = 'SETTINGS_OTHER_ACCOUNT_SEND_EMAIL';
export const SETTINGS_OTHER_ACCOUNT_SEND_USERNAME = 'SETTINGS_OTHER_ACCOUNT_SEND_USERNAME';
export const SETTINGS_OTHER_ACCOUNT_SEND_PASSWORD = 'SETTINGS_OTHER_ACCOUNT_SEND_PASSWORD';
export const SETTINGS_OTHER_ACCOUNT_DELETE_ACCOUNT = 'SETTINGS_OTHER_ACCOUNT_DELETE_ACCOUNT';
