export const TEST_FETCH_DATA = 'TEST_FETCH_DATA';
export const TEST_INSIDE_FETCH_DATA = 'TEST_INSIDE_FETCH_DATA';
export const TEST_INSIDE_SEND_DATA = 'TEST_INSIDE_SEND_DATA';
export const TEST_INSIDE_SEND_FEEDBACK = 'TEST_INSIDE_SEND_FEEDBACK';
export const TEST_INSIDE_FETCH_WHO_AM_I = 'TEST_INSIDE_FETCH_WHO_AM_I';
export const TEST_INSIDE_WIPE_WHO_AM_I = 'TEST_INSIDE_WIPE_WHO_AM_I';