export const FETCH_USER = 'FETCH_USER';
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const DASHBOARD_SEND_TOOLS = 'DASHBOARD_SEND_TOOLS';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const SET_STATUS = 'SET_STATUS';
export const SET_IDENTIFIER = 'SET_IDENTIFIER';
export const CHANGE_IDENTIFIER_NAME = 'CHANGE_IDENTIFIER_NAME';
export const WIPE_IDENTIFIER = 'WIPE_IDENTIFIER';
