const personalityGeneralQuestions = [
    "You enjoy being the center of attention",
    "You like to make things simple",
    "You sympathize with the homeless",
    "You like to do things as they were done in the past",
    "You forgive easily",
    "You enjoy philosophical discussions",
    "You avoid arguing, even when You disagree",
    "You like to spend your free time alone",
    "You believe people should be punished for their mistakes",
    "You have a lot of energy",
    "You Believe in After life",
    "You are sensitive to the feelings of others",
    "You are easily distracted",
    "You have a zest for life",
    "You wonder why You are the way You are",
    "You let others know that You care about their feelings",
    "You are full of new ideas",
    "You are a risk taker",
    "You Have difficulty understanding abstract ideas",
    "Seeing other people cry can easily make you feel like you want to cry too",
    "You prefer to completely finish one project before starting another",
    "Even a small mistake can cause you to doubt your overall abilities and knowledge",
    "You are more inclined to follow your head than your heart",
    "You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine",
    "You usually worry about whether you make a good impression on people you meet",
    "You enjoy participating in group activities",
    "It’s important for you to be on time all the time",
    "You avoid leadership roles in group settings",
    "You usually find yourself lost in your thoughts, worrying about many things",
    "There are things that you know you’re very good at them (or one thing)",
    "You prefer to do your chores before allowing yourself to relax",
    "You believe hard work is very important for success and you try to work as hard as possible",
    "You tend to take it out on others when you've had a bad day",
    "Your mood can change very quickly",
    "You Believe in God",
    "You usually postpone finalizing decisions for as long as possible",
    "You often have a hard time understanding other people’s feelings",
    "You exercise frequently",
    "You are still bothered by mistakes that you made a long time ago",
    "You feel confident that things will work out for you"
];

module.exports = personalityGeneralQuestions;